{% set build = 0 %}
{% set name = "gpaw" %}
{% set version = "20.1.0" %}
{% set sha256 = "c84307eb9943852d78d966c0c8856fcefdefa68621139906909908fb641b8421" %}
{% set build_string = "py{}_{}_{}".format(environ.get('CONDA_PY', ''), mpi, build) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 001_config-py.patch
    # patch 001 is needed because gpaw's config.py assumes that libpython is a dynamic library,
    # whereas the python version used by conda-forge provides a static library. Hopefully gpaw-devs
    # will accept this as a future change upstream.

build:
  number: {{ build }}
  string: {{ build_string }}
  skip: True  # [not linux]
  skip: True  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - {{ mpi }}  # [mpi != 'nompi']
    - python
    - pip
    - libxc <5.0
    - libblas
    - libcblas
    - scalapack
    - fftw
    - numpy
    - ase
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - python
    - libxc <5.0
    - libblas
    - libcblas
    - scalapack
    - fftw
    - {{ pin_compatible('numpy') }}
    - scipy
    - ase
    - gpaw-data

test:
  commands:
    - python -m pip check
    - gpaw test -j 1 --reverse --from generic/mixer.py                          # [mpi == 'nompi']
    - test -x $PREFIX/bin/gpaw                                                  # [mpi != 'nompi']
    - export OMPI_MCA_plm=isolated                                              # [mpi == 'openmpi']
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none                      # [mpi == 'openmpi']
    - export OMPI_MCA_rmaps_base_oversubscribe=yes                              # [mpi == 'openmpi']
    - mpiexec -np 1 python -m gpaw test --reverse --from generic/mixer.py       # [mpi != 'nompi']

about:
  home: https://wiki.fysik.dtu.dk/gpaw
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'GPAW: DFT and beyond within the projector-augmented wave method'
  description: |
    GPAW is a density-functional theory (DFT) Python code based on the
    projector-augmented wave (PAW) method and the atomic simulation environment
    (ASE). It uses plane-waves, atom-centered basis-functions or real-space
    uniform grids combined with multigrid methods.
  doc_url: https://wiki.fysik.dtu.dk/gpaw/documentation/documentation.html
  dev_url: https://gitlab.com/gpaw/gpaw

extra:
  recipe-maintainers:
    - bjodah
    - jan-janssen
