conda_forge_output_validation: true
bot:
  automerge: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: default
build_platform:
  linux_aarch64: linux_64
